apiVersion: v1
kind: ConfigMap
metadata:
  name: budgeometre-config
  namespace: u-grp5
data:
  POSTGRES_USER: "budgeometre_user"
  POSTGRES_DB: "budgeometre_db"
  ECRITURE_SERVICE_URL: "http://ecriture-service:5001"
  LECTURE_SERVICE_URL: "http://lecture-service:5002"