apiVersion: v1
kind: Secret
metadata:
  name: budgeometre-secrets
  namespace: u-grp5
type: Opaque
stringData:
  POSTGRES_PASSWORD: "budgeometre_pass_2024"
  SECRET_KEY: "budgeometre-secret-key-change-me-in-production"
  DATABASE_URL: "postgresql://budgeometre_user:budgeometre_pass_2024@postgres-service:5432/budgeometre_db"