# HPA pour Gateway
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
---
# HPA pour Ecriture
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ecriture-hpa
  namespace: budgeometre
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ecriture-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
---
# HPA pour Lecture
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lecture-hpa
  namespace: budgeometre
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lecture-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
